# Generated by Django 3.1 on 2020-09-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200818_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_event',
            name='event_id',
        ),
        migrations.AddField(
            model_name='create_event',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
